name: ServerQuiz
version: '1.1.2'
main: org.rd806.serverquiz.ServerQuiz
api-version: '1.20'
softdepend: [ Vault ]
authors: [ RunicDolphin806 ]

commands:
  serverquiz:
    aliases: quiz

permission:
  # 回答权限
  serverquiz.open:
    default: true
  # 查看权限
  serverquiz.show:
    default: false
  # 编辑权限
  serverquiz.edit:
    default: false
